services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "13306:3306"
    networks:
      - laravel_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data: